---
- name: install basics
  hosts: servers
  become: true
  become_user: root
  gather_facts: true
  yum: state=present name={{ item }}
  with_items:
          - epel-release
          - screen
          - vim
          - openssl
          - net-tools
          - nmap
          - wget
          - curl
          - unzip
          - rsync
          - mlocate
          - telnet
          - glaces
          - htop
          - jq
          - git  
             
